# Generated by Django 4.2.3 on 2023-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=20, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Unit_measure', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
