# Generated by Django 4.2.3 on 2023-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True)),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
